### ISSUE TITLE
New water source artwork

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#104]
From #93 

> @samreid just as a heads up, the team decided to iterate on the water source with the graphic artist. It will have similar dimensions to the hose, but it won't be the hose itself.

Assigned to @arouinfar to check on the status of the artwork.

**Comment by arouinfar** [comment]
@samreid the water source asset is ready for implementation. Here's a mockup showing it in context.

![screen shot 2018-10-15 at 11 32 46 am](https://user-images.githubusercontent.com/8419308/46967547-14dfee80-d06e-11e8-91f6-1050afc45de6.png)

I've made the asset a bit long so that its end won't be visible unless at very wide aspect ratios, similar to the faucet in concentration:
![image](https://user-images.githubusercontent.com/8419308/46967798-cb43d380-d06e-11e8-8321-a1d092b1872f.png)

I've temporarily stored the assets on Drive, and they will be deleted once checked in.
https://drive.google.com/drive/u/0/folders/1iynU6kf034JBHEnPVUpmppuaMhiEQHua

**Comment by samreid** [comment]
At yesterday's meeting, we decided we would like to try using the same faucet, but with a button on the body of the pipe instead of a plunger on the top.

**Comment by arouinfar** [comment]
@samreid I've updated the assets on Drive, so back to you! :)

**Comment by samreid** [comment]
It looks like scenery-phet has very similar or identical assets for this, I'd like to try that first to see if it will work.

**Comment by arouinfar** [comment]
Sounds good @samreid. I modified the .ai file for faucetNode by removing the slider bit at the top, so if you can use what's already in scenery-phet, go for it. Here's a mockup showing the  updated water source in context:

![image](https://user-images.githubusercontent.com/8419308/47302104-e322d680-d5dd-11e8-9698-b26d25bfebdc.png)

**Comment by samreid** [comment]
Initial draft pushed and ready for review.  @arouinfar can you please check phettest and provide feedback?

**Comment by arouinfar** [comment]
The team liked the updated water source, we we can close this issue.
