### ISSUE TITLE
Random blobs for the diffraction screen

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#139]
We could try premaking blobs and see how they transform.  Maybe a Swiss cheese one?  Maybe a strobe logo one?

**Comment by samreid** [comment]
Assigned to @arouinfar to experiment with some shapes using http://turbomaze.github.io/JS-Fourier-Image-Analysis/ and to recommend some patterns.

**Comment by arouinfar** [comment]
We didn't have time for this in design meeting today, and it's probably best to discuss when @ariel-phet is around, so we'll need to prioritize this issue next design meeting. 


I've done some preliminary exploration, and can think of some general observations:
* Translating a shape doesn't really change the FFT
* The size of the shape changes how much detail is seen (smaller = more zoomed in detail in FFT)
* Combining shapes with known diffraction patterns (circles and squares) results in patterns with easier to interpret features
* It's practically impossible to extract meaningful information (with the naked eye) from the FFT of more abstract images.

Here are some of my favorite tests, with the original image on the left, and FFT on the right. (See [FFT_Examples.pdf](https://github.com/phetsims/wave-interference/files/2517061/FFT_Examples.pdf) for the full results.)
![test3_fft](https://user-images.githubusercontent.com/8419308/47535443-e4236480-d878-11e8-8929-67c5c171c9e6.png)
![test5_fft](https://user-images.githubusercontent.com/8419308/47535444-e4bbfb00-d878-11e8-8d68-6bd86d032ce4.png)
![test15_fft](https://user-images.githubusercontent.com/8419308/47535445-e4bbfb00-d878-11e8-9d80-0e607a6ad9a2.png)
![test24_fft](https://user-images.githubusercontent.com/8419308/47535447-e4bbfb00-d878-11e8-8145-0ca1630462bc.png)
![test19_fft](https://user-images.githubusercontent.com/8419308/47535446-e4bbfb00-d878-11e8-8ff1-33882b317460.png)
![test20_fft](https://user-images.githubusercontent.com/8419308/47535507-1af97a80-d879-11e8-8bac-19173afd1c95.png)

**Comment by arouinfar** [comment]
I'd like to come up with a set of ~10 images that best demonstrates my observations in https://github.com/phetsims/wave-interference/issues/139#issuecomment-433235620, so leaving myself assigned for now.

**Comment by arouinfar** [comment]
The current design has five radio options for different diffraction targets. Mockups can be found in the design doc.

1. Circle - adjustable diameter (or major axis) and eccentricity
2. Square - adjustable length and width
3. Circle & Square - adjustable diameter/side length for each
4. 4x4 Lattice of Circles - adjustable diameter, spacing between circles, and disorder (described below)
5. Waving Girl - adjustable height (image will scale proportionally) and rotation (0* is fully upright)

For the lattice, the "disorder" slider is snappy. Originally, we had discussed having a slider with 9 tick marks, the first being 0 disorder, and 8 levels of disorder thereafter. At each non-zero tick mark, 2 cells would be perturbed, and at max disorder all 16 cells would be perturbed.  I used a random number generator and coin toss simulator to generator a list of perturbations to the lattice (displacement in the x and y directions, and eccentricity). 

I then ran the FFT for 4 variations: dense vs. sparse spacing, large vs. small circles. You can see the full results here:
[FFT_Dense_Lattice.pdf](https://github.com/phetsims/wave-interference/files/2954160/FFT_Dense_Lattice.pdf)
[FFT_Sparse_Lattice.pdf](https://github.com/phetsims/wave-interference/files/2954161/FFT_Sparse_Lattice.pdf)

In general, I think 8 tick marks is too many. Here are the results for 4 levels of disorder, with 4 cells being disturbed each time.

<details>
<summary><b>Expand to see FFT results</b></summary>

![lattice_1](https://user-images.githubusercontent.com/8419308/54157452-f9ef8b80-440d-11e9-8529-3e4e7feec777.png)
![lattice_1b](https://user-images.githubusercontent.com/8419308/54157454-f9ef8b80-440d-11e9-82f0-624310987b9c.png)
![lattice_1d](https://user-images.githubusercontent.com/8419308/54157457-fb20b880-440d-11e9-873f-83059b5a001a.png)
![lattice_1f](https://user-images.githubusercontent.com/8419308/54157458-fb20b880-440d-11e9-82d1-e1d3fec44e82.png)
![lattice_1h](https://user-images.githubusercontent.com/8419308/54157463-fbb94f00-440d-11e9-89c9-0b562be3a155.png)
![lattice_2](https://user-images.githubusercontent.com/8419308/54157465-fbb94f00-440d-11e9-9cb3-6a1176f2f924.png)
![lattice_2b](https://user-images.githubusercontent.com/8419308/54157466-fbb94f00-440d-11e9-93d3-a25035dc7137.png)
![lattice_2d](https://user-images.githubusercontent.com/8419308/54157467-fbb94f00-440d-11e9-9d5e-371accdb769d.png)
![lattice_2f](https://user-images.githubusercontent.com/8419308/54157469-fc51e580-440d-11e9-8fa5-c067cdcaf4b6.png)
![lattice_2h](https://user-images.githubusercontent.com/8419308/54157470-fc51e580-440d-11e9-92fd-98aff223c68e.png)
![lattice_3](https://user-images.githubusercontent.com/8419308/54157471-fcea7c00-440d-11e9-8ace-862a00069562.png)
![lattice_3b](https://user-images.githubusercontent.com/8419308/54157472-fcea7c00-440d-11e9-803e-b6f936ea09ee.png)
![lattice_3d](https://user-images.githubusercontent.com/8419308/54157473-fcea7c00-440d-11e9-9492-18cb59b4cdc9.png)
![lattice_3f](https://user-images.githubusercontent.com/8419308/54157474-fd831280-440d-11e9-8244-28ba0c78be1d.png)
![lattice_3h](https://user-images.githubusercontent.com/8419308/54157475-fd831280-440d-11e9-844b-8936f51bbb30.png)
![lattice_4](https://user-images.githubusercontent.com/8419308/54157476-fd831280-440d-11e9-97c3-2e97e0df1be8.png)
![lattice_4b](https://user-images.githubusercontent.com/8419308/54157477-fd831280-440d-11e9-94a1-402b26770b4c.png)
![lattice_4d](https://user-images.githubusercontent.com/8419308/54157478-fd831280-440d-11e9-9bcb-50dad155cc39.png)
![lattice_4f](https://user-images.githubusercontent.com/8419308/54157479-fd831280-440d-11e9-886d-29ec2170debd.png)
![lattice_4h](https://user-images.githubusercontent.com/8419308/54157480-fd831280-440d-11e9-9f00-ced59aa431ba.png)
</details> 
<br>

@samreid here are the specs for each tick mark:

| Tick Mark | Cell [row, column] | x-displacement | y-displacement | Eccentricity |
| --- | --- | --- | --- | --- | 
| 2 | [1, 2] | 0% | -45% | -- | 
| 2 | [1, 4] | -35% | -45% | -- | 
| 2 | [2, 3] | 10% | 0% | -- | 
| 2 | [3, 4] | 30% | 40% | -- | 
| 3 | [1, 1] | -50% | -70% | 45%-y | 
| 3 | [1, 3] | 40% | 0% | -- | 
| 3 | [3, 2] | 0% | -60% | -- | 
| 3 | [4, 1] | -40% | -45% | 40%-y | 
| 4 | [2, 1] | 55% | 55% | -- | 
| 4 | [3, 1] | -55% | -45% | 45%-x | 
| 4 | [4, 3] | 35% | 45% | 50%-x | 
| 4 | [4, 4] | -65% | 60% | -- | 
| 5 | [2, 2] | -75% | -65% | 70%-y | 
| 5 | [2, 4] | 65% | 65% | 60%-y | 
| 5 | [3, 3] | 60% | -75% | 50%-x | 
| 5 | [4, 2] | -60% | 70% | 75%-x | 

**Tick Mark**: The disorder slider has 5 tick marks. The first tick mark represents zero disorder, and will correspond to an unperturbed lattice. The perturbations are cumulative, a lattice with disorder set to max would have all 16 cells disturbed.

**Cell**: Coordinate representation of the row and column indices expressed as [row, column]. A value of [3, 1] represents the circle in the third row, first column.

**Displacement**: Because the lattice has a variable separation, the displacements are specified as a percentage. If the lattice separation is 20 px, a displacement of 25% would be 5 px. The positive direction is to the right and up.

**Eccentricity**: These values are expressed as the ratio of the minor axis to the major axis. A value of 50%-x means that the x-axis is 50% of the length of the y-axis. For a circle diameter of 100 px, this would translate into an ellipse with a vertical major axis of 100 px, and horizontal minor axis with a length of 50 px.

**Comment by arouinfar** [comment]
Assigning to @samreid for review/implementation. Please let me know if you have any questions, or would like to discuss over zoom.

**Comment by samreid** [comment]
I've implemented a very rough draft and am ready for initial feedback from @arouinfar.  Known remaining issues:
* I did not match the coordinate frame as in the design document--not sure if that is worth any effort, please let me know
* The design doc shows lattice spacing 0->1000nm, should this be more like 1000->200nm?  Or make it more qualitative?
* General feedback, anything else to do for this scene?

**Comment by samreid** [comment]
I'm going to reimplement this using a strategy that gives better performance and a smoother result. Things may end up looking a little different. Removing "ready-for-review" label until the change is complete.

**Comment by arouinfar** [comment]
@samreid I currently have this issue earmarked for my flight back on Friday. If you finish up the implementation by Thursday, can you publish a new dev version?

>The design doc shows lattice spacing 0->1000nm, should this be more like 1000->200nm? Or make it more qualitative?

200-1000 sounds like a much more reasonable range, so let's give that a try. I likely copied and renamed one of the other NumberControls in the mockups, without fixing a range.

**Comment by samreid** [comment]
I'm trying to publish a new dev version, but running into unknown problems, detailed in https://github.com/phetsims/wave-interference/issues/360.  Not sure if I'll have a dev version ready by then--I'll keep you posted.

**Comment by arouinfar** [comment]
No worries @samreid! I have plenty of other things I can catch up on. 😄

**Comment by samreid** [comment]
I published a dev version here which uses the strategy described in #355, ready for feedback:
https://phet-dev.colorado.edu/html/wave-interference/1.1.0-dev.2/phet/wave-interference_en_phet.html

**Comment by arouinfar** [comment]
Excellent, thanks @samreid! I will review it tomorrow.

**Comment by arouinfar** [comment]
@samreid everything is looking good. I'll tag for design meeting for review with the rest of the team.

**Comment by samreid** [comment]
@kathy-phet said it looks good.
@ariel-phet said it gets the point across.

@kathy-phet points out that once we have an initial version, we could present this to our collaborators.

**Comment by samreid** [comment]
I recommend we close this issue, should we open a new issue to track what to discuss with our collaborators?

**Comment by arouinfar** [comment]
Sounds reasonable to me @samreid! Let's close.
