### ISSUE TITLE
Show falling water drops

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#15]
@ariel-phet and @arouinfar it would be nice to have good raindrop artwork.  Maybe a good task for our artist?

**Comment by arouinfar** [comment]
@ariel-phet @samreid Mariah created a water droplet icon for SOM, and I think it would also work for Wave Interference.
https://github.com/phetsims/states-of-matter/blob/master/images/liquid-icon.png
https://github.com/phetsims/states-of-matter/blob/master/assets/liquid-icon.ai

![image](https://user-images.githubusercontent.com/8419308/36911971-80b1254e-1e02-11e8-993d-df528b24358b.png)

**Comment by arouinfar** [comment]
@ariel-phet @samreid what would you think about re-using this artwork?

**Comment by samreid** [comment]
It seems good to me--let's try it in context.

**Comment by kathy-phet** [comment]
All, I’m personally inclined to leave it like the Java version because pedagogically the immediate feedback and connection between setting the slider values and seeing a change in behavior in the wave is so valuable. A delay in response would make that a bit harder for students. I haven’t been bothered by those visuals in Java. The ease of implementation is also a bonus.

Sent from my iPhone

On Aug 5, 2018, at 8:18 AM, Sam Reid <notifications@github.com<mailto:notifications@github.com>> wrote:


In the Java version, the frequency, amplitude, on/off controls determine what is happening on the lattice immediately, and the water drops "lag behind" the current values. For instance, when the Java simulation launches, the water is already oscillating even before the first water drop hits. If you increase the frequency, the lattice frequency changes immediately, even before the more rapid succession of drops hits. This implementation was chosen not because it was physically accurate, but because it was easier to implement. In HTML5 we could use this same strategy or try a more causal relationship. If we try for the causal relationship, one way to implement it may be to have the frequency/amplitude/on-off controls set a "requested value" that gets stored in a water drop (instead of setting the lattice value immediately), and when that water drop hits the lattice, then it makes the change to the lattice source. That strategy would not allow for continuous changing of the frequency or amplitude, because the values would only change when the water drops hit the lattice.

The water-drop based model seems more physically accurate and I'm inclined to investigate it, but wanted to get feedback from the design team first. @arouinfar<https://github.com/arouinfar> @ariel-phet<https://github.com/ariel-phet> @kathy-phet<https://github.com/kathy-phet> what do you think?

**Comment by samreid** [comment]
I'm investigation behavior like the Java solution, but it also occurred to me there is a 3rd option:

(3) When changing the frequency of the emitter, immediately create new water drops in the air corresponding to the appropriate splash times.  It may be odd for drops to appear in the air (not out of the hose), but then they would hit the lattice at the right times (instead of a delay).  I don't know if this would be an overall improvement or a lateral move, so I thought I'd mention it.

That being said, I'm getting close to completing the solution as in the Java version, so we should be able to test that out soon.

**Comment by samreid** [comment]
For (3), a main advantage seems to be clearing out the old drops that don't match the newly set frequency.

**Comment by samreid** [comment]
I'll commit what I have for now and postpone further work until we have discussed (3).

**Comment by samreid** [comment]
We agreed we will automatically update the drops in the air, according to https://github.com/phetsims/wave-interference/issues/15#issuecomment-410761082

**Comment by arouinfar** [comment]
@samreid it's looking really nice! I don't see a problem with the initial phase. I think the remaining work all depends on the finalized artwork, so I'll leave it up to you to close now or mark as on-hold until you have updated assets.

**Comment by samreid** [comment]
I'll close this one and work on updated assets in #51

**Comment by samreid** [comment]
Sorry, #51 doesn't seem quite right.  I'll create a new issue.
