### ISSUE TITLE
Consider adding wavelength readout to scenes with Light

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/wave-interference#152]
I was thinking perhaps we could add some sort of wavelength readout to the scenes with light. Although I like the frequency slider, and I think it keeps things consistent and pedagogically correct (since the frequency is really the constant quantity) being able to know the wavelength also seems relevant, since diffraction tends to happen when features are "on the order" of the wavelength. I was thinking that perhaps above the laser pointer we could have something like `lamba=wavenlength`

Thoughts @arouinfar

**Comment by arouinfar** [comment]
@ariel-phet in general, I like this suggestion. I do worry, however, that single-slit diffraction is better observed at a = 2 or 3 λ. I think this is partly due to the screen being relatively close to the slits. I'll tag for further discussion at design meeting.

### a ~ λ
<img width="813" alt="screen shot 2018-09-25 at 3 40 35 pm" src="https://user-images.githubusercontent.com/8419308/46044951-78af7100-c0d9-11e8-909a-85dc12f49f3d.png">

### a ~ 2λ
<img width="815" alt="screen shot 2018-09-25 at 3 39 26 pm" src="https://user-images.githubusercontent.com/8419308/46044866-3be37a00-c0d9-11e8-93a0-98c6dd807af9.png">

### a ~ 3λ
<img width="813" alt="screen shot 2018-09-25 at 3 41 57 pm" src="https://user-images.githubusercontent.com/8419308/46044983-9086f500-c0d9-11e8-8362-43e28d8510f1.png">

**Comment by arouinfar** [comment]
@ariel-phet we discussed this during today's design meeting. The general consensus was that this feature isn't strictly necessary.

Single-slit diffraction is best observed at a > 2λ (or d > 2λ for double-slit interference) -- see https://github.com/phetsims/wave-interference/issues/152#issuecomment-424516291 for screenshots. Supplying the precise λ value may not actually help. 

Qualitatively, the scale bar makes it pretty clear that wavelengths are about 500 nm, give or take. @kathy-phet would prefer that students look at the wave and slit in the viewing area, than the precise values of `λ` and `a` or `d`.

Thoughts @ariel-phet?

**Comment by ariel-phet** [comment]
Since the equations we teach are basically d*sin(theta) = m(lambda) I think not being able read out lambda is problematic.

**Comment by arouinfar** [comment]
@ariel-phet and I discussed this issue a bit more today.

Initially, @ariel-phet had been thinking about using the λ readout to verify the equations. However, Java doesn't provide any quantitative measure for wavelength, and this feature wasn't a teacher request. 

We decided not to include the λ readout, but would be open to revisiting this discussion if this became a frequent teacher request in the future.
