### ISSUE TITLE
Are the scenes synchronized?

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#16]
Does changing the frequency in the Water scene also change the frequency in the Sound scene?  Does it change the wavelength in the Light scene?

**Comment by arouinfar** [comment]
That's an excellent question @samreid, and I've been giving it a bit of thought.

I think it makes the most sense for the states to be separate. For example, maxing out frequency in sound scene will not affect the frequency in the water scene. When switching scenes, the wave animation could start over.

Certain controls should be global, however, including:
* Continuous/pulse
* Top/side-view
* Graph visibility
* Tools
* Play/pause/playback speed

**Comment by samreid** [comment]
> For example, maxing out frequency in sound scene will not affect the frequency in the water scene.

I'm happy to proceed as you recommended but would love to hear your reasoning about making the frequency/amplitude independent in each scene.

**Comment by samreid** [comment]
We discussed this at yesterday's design meeting.  The proposed philosophy is that when switching between water, sound and light, the wave representation should look predominantly the same (same amplitude, same frequency, same source position), because the user will mainly want to focus on the difference in medium, rather than changing lots of variables at once.

We decided based on the need for the light to deal with a single frequency that the waves should restart when switching medium.  Once this is implemented, we'll evaluate and make sure it's desirable.

In order to cue the student about the different scales, a scale indicator will be added (possibly at the top left) to indicate the relative scales.

**Comment by arouinfar** [comment]
Thanks for summarizing @samreid!  A few other points we discussed:
* We'll most likely call the wavelength slider on the Light scene "Frequency". This would provide better consistency with the other scenes, and as @ariel-phet pointed out, it could be considered more accurate because the frequency of light is unchanged by its medium.
* Turning on the continuous source in one scene will turn it on in all scenes. This provide a more streamlined UX, preventing users from having to make an extra click.
* When switching scenes, the wave will clear and re-propagate (as it does when changing the frequency in the light scene). This is important because the frequency slider is common between all scenes, and changing the frequency of water waves will change the color of the light. If the wave animation continued when switching back to light, users would see colors mixing, which is complicated and not pedagogically useful.

**Comment by arouinfar** [comment]
Additionally, we decided to have the wave source on at startup. The wave will propagate from the source, similar to Java, like so:
![image](https://user-images.githubusercontent.com/8419308/37226659-ed3f1280-2397-11e8-9b10-c092001e1ad2.png)
![image](https://user-images.githubusercontent.com/8419308/37226682-014d53e0-2398-11e8-8fdd-dbdfa9f98353.png)
![image](https://user-images.githubusercontent.com/8419308/37226694-0a3a3108-2398-11e8-94a3-58e122e7ad71.png)

**Comment by samreid** [comment]
As far as I can tell, we have achieved all of the recommendations in the prior comments, closing.
