### ISSUE TITLE
Wave source on/off for each scene should be independent

### ISSUE THREAD

**Issue by arouinfar** [phetsims/wave-interference#179]
While playing with the sim in design meeting, @kathy-phet noticed that turning the source on in once scene also turned it on for other scenes.

This behavior seems a bit strange, given that the scenes are otherwise independent from each other.

We decided it made the most sense for the scenes to have independent on/off buttons so the user needs to take the action to turn the source on.

**Comment by samreid** [comment]
Just moving `button1PressedProperty` and `button2PressedProperty` from WavesScreenModel to Scene may do the trick, but there is a lot of logic in WavesScreenModel that was leveraging this.  Also, how far should we go in moving the logic?  Should each scene have its own Lattice?

**Comment by samreid** [comment]
There are some other features that are currently shared across scenes, and in order to implement this it would be good to know which other features should be independent vs shared across scenes

* Amplitude
* Pulse vs Continuous selection
* The tools (measuring tape, stopwatch, wave detector)
* Graph (on/off)
* Play/pause button state
* Normal/Slow selection
* Slits selection (no barrier/one slit/two slits)

@arouinfar can you please comment, or let me know if we should escalate this to a design meeting topic?

**Comment by arouinfar** [comment]
* Amplitude - Independent 
* Pulse vs Continuous selection - Global
* The tools (measuring tape, stopwatch, wave detector) - Global
* Graph (on/off) - Global
* Play/pause button state - Global
* Normal/Slow selection - Global
* Slits selection (no barrier/one slit/two slits) - Independent

**Comment by samreid** [comment]
First draft of this work is committed and pushed.  It was a relatively complicated and extensive changed, and it should be tested thoroughly.  @arouinfar can you please review on phettest?

**Comment by arouinfar** [comment]
@kathy-phet this is the issue that @samreid was talking about in status.

**Comment by arouinfar** [comment]
Everything looks great @samreid. Thanks!
