### ISSUE TITLE
Instead of “water level” do you think “water height” would be clearer for students?

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#19]
What age/grade level is the target for this simulation?

**Comment by arouinfar** [comment]
@samreid the sim is primarily designed for high school and university students. However, waves are commonly taught in middle school, so some teachers may use Wave Interference (though WOAS or BL could also be leveraged). In particular, I think the Waves and Interference screens could be used in middle school classrooms, so it would be good to keep younger learners in mind and be accommodating, where possible. 

Java uses "Water Level" which is why that string made it into the mockups. However, I think "Water Height" conveys the same message, and would perhaps be clearer to students regardless of grade level. I'd be in favor of using "Water Height" @samreid. Great suggestion.

**Comment by samreid** [comment]
I renamed existing occurrences in the sim and will try to remember to update other ones as I go.
