### ISSUE TITLE
Should the chart extend a little beyond the wave area? 

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#20]
Should the chart extend a little beyond the wave area?  Right now the horizontal axis labels "0" and "10" are partway on partway off and it looks odd:

![image](https://user-images.githubusercontent.com/679486/37051869-e3399cb6-2134-11e8-9527-8df9384bae77.png)

**Comment by arouinfar** [comment]
@samreid it's important that the x-axis lines up with the wave viewing window, even though it will leave the 0/10 a bit stranded on the edges.

One alternative would be to enclose the entire graph in a light gray background:
![image](https://user-images.githubusercontent.com/8419308/37059410-9df59bf8-214a-11e8-9b79-71ed71002db5.png)

Another option would be to offset the 0 and 10 a bit so that they're not centered below their respective gridlines:
![image](https://user-images.githubusercontent.com/8419308/37059585-147ecf92-214b-11e8-808b-a92e5665925e.png)

The first option would make the graph a bit heavier overall, and the second option would break axis-labelling convention a bit, but I could live with either.

**Comment by samreid** [comment]
The first option still looks odd at "0" and "10" but it's not clear which is better.  Here's how it looks in the sim at the moment (I know it's still not a perfect match):

![image](https://user-images.githubusercontent.com/679486/37061697-7fe66c94-2151-11e8-91be-84cace56f6a3.png)

I'm inclined to ask @kathy-phet and/or @ariel-phet opinion before spending more time on it.  Sound OK?  If so, please assign accordingly.

**Comment by arouinfar** [comment]
@samreid nice progress! Let's discuss the graph at design meeting this week. These issues mostly seem like pixel polishing, so I think it can wait a few days until then.  If not, please reassign me.

**Comment by samreid** [comment]
Bubble out around on the left and right side, like in the top one on https://github.com/phetsims/wave-interference/issues/20#issuecomment-370936580 but keeping the top and bottom tabs.

**Comment by samreid** [comment]
And make it more transparent.

**Comment by samreid** [comment]
Fixed after preceding commits, @arouinfar can you please take a look on phettest?

**Comment by arouinfar** [comment]
Looks good, thanks @samreid!
