### ISSUE TITLE
Unify step size across scenes

### ISSUE THREAD

**Issue by arouinfar** [phetsims/wave-interference#226]
I noticed that the step forward button is on a different time scale across scenes, which feels really odd. 

Water: 0.05 s
Sound: 0.115 ms? Steps alternate between 0.11 and 0.12 ms.
Light: 0.14 fs

The step size for Sound and Light doesn't seem very optimal. @samreid can we use 0.05 time units for all three scenes?

**Comment by arouinfar** [comment]
If for some reason 0.05 ms/fs is not feasible for Sound/Light, I'd also be fine with a step size of 0.1 time units for all three scenes.

**Comment by samreid** [comment]
Proposed fix pushed, @arouinfar can you please review and test?

**Comment by samreid** [comment]
Reopening to investigate if this change broke https://github.com/phetsims/wave-interference/issues/254

**Comment by samreid** [comment]
I don't think we can fix this.  The step time must be exactly 1/STEP_TIME so that the step button behavior will match the running behavior.  See #254.  The other variable we have is `this.sceneProperty.value.timeScaleFactor`, but that is determined by the wave speed.  Therefore I recommend we close this issue as "will not fix".  @arouinfar can you please review and discuss?

**Comment by arouinfar** [comment]
Understood @samreid. The behavior in #254 is definitely problematic, and different step sizes across scenes is at worst somewhat inconvenient.
