### ISSUE TITLE
address REVIEW comments

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/wave-interference#269]
Related to code review #259.

I'm adding `//REVIEW` comments for things that don't warrant a GitHub issue.  Close this issue when those comments have been addressed and removed.

**Comment by samreid** [comment]
From slack conversation:

> I would like to have a straightforward protocol (without too much overhead) for you to be able to verify/validate my changes.

For now, I'd like to make `//REVIEW*` comments where I have addressed a `//REVIEW` comment.  @pixelzoom can search for this string to see where threads require feedback/discussion/verification.  Threads that are completed satisfactorily can be deleted.

**Comment by samreid** [comment]
My comment https://github.com/phetsims/wave-interference/issues/269#issuecomment-448458817 is getting buried in commits.  Summarizing relevant points:

1. I've made many commits, please pull before resuming review
2. Please notify me when you resume the review so that I can hold off on further commits
3. My responses to review comments have an asterisk: `REVIEW*`
4. Review comments you made that I haven't addressed yet have a caret `REVIEW^`
5. If a `REVIEW` comment has been satisfactorily resolved, please delete that thread.
6. If you add new review comments, please use `REVIEW^` to indicate the ball is in my court for that comment.

I'll also comment this protocol on slack.

**Comment by pixelzoom** [comment]
@samreid I've reviewed all of your replies to REVIEW comments since yesterday. All remaining REVIEW comments that require your response can be identified by searching for "REVIEW^".

**Comment by samreid** [comment]
All `//REVIEW` comments addressed, please review.  Close if all is well.

**Comment by pixelzoom** [comment]
All REVIEW threads have been reviewed and deleted.  Our work here is done.  Closing.
