### ISSUE TITLE
Lesson Example: Use of reflecting barrier

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/wave-interference#294]
One good lesson that we are currently highlighting an an article uses the Wave Interference capability of going to no slit at all to look at a reflecting barrier - and drawing parallels to the behavior in wave on a string reflection. 

Right now the new version would not support this aspect of this lesson. Just noting it for consideration. You can see that the in the center the reflected wave adds to have higher amplitude than the original.

![image](https://user-images.githubusercontent.com/5096804/50367912-d7ea1980-0540-11e9-80ee-f9b5431c9e02.png)

**Comment by arouinfar** [comment]
@kathy-phet the barrier is not reflective, by design. See #13:

> The barriers in the model currently force the lattice values to constant value of 0, this has the effect of reflecting the waves. Instead we would prefer that the barriers (say, for the double slit) absorb the wave instead of reflect it--this will help students focus on the interference on the opposite side of the slits instead of the complex reflective pattern on the incident side of the slits.

Making the barrier absorbing also addressed the issue of distracting reflections that had been reported by Wendy Adams in #38.

Setting the slit width to zero also had strange artifacts in the lattice where the plane wave would still leak through. I tried finding an issue for this, but couldn't. Tagging @samreid in case he remembers. You can test it for yourself in [dev.42](https://phet-dev.colorado.edu/html/wave-interference/1.0.0-dev.43/phet/wave-interference_en_phet.html) (or earlier).

![image](https://user-images.githubusercontent.com/8419308/50379397-10076000-0606-11e9-8fe7-29d4194553cb.png)

We considered a mirror in the [4/12/18](https://docs.google.com/document/d/1Lr5A7LG8PyrTHD5tC0Ux4IP9nF7XrE-bZTyRIc7Yc2A/edit#heading=h.uaqoparxce8w) design meeting, but ultimately decided against it. A mirror is not compatible with the current model, and I do not think this is something we could add by the Jan 31 deadline. If you feel strongly about its inclusion, we can revisit in design meeting and consider for 2.0.

**Comment by arouinfar** [comment]
>  If we want to support reflection, it should be through a separate feature, such as adding a "Mirror" entry in the combo box

That's what I was thinking. Could you give a time estimate for adding such a feature @samreid? 

> I don't think we should have a mirror with slits.

Agreed @samreid.

**Comment by samreid** [comment]
The main complication is that for the case of the absorbing barrier, we have an analytical model for plane waves left of the barrier.  If we introduce an emergent model in that same area, it will very likely look and behave differently than the analytical model (due to internal reflections at the top, bottom and left).  Alternatively, we could stick with an analytical model on the left, and incorporate the reflection into the analytical model--that may be more straightforward and we wouldn't have to deal with distracting reflections like https://github.com/phetsims/wave-interference/issues/38 or edge effects.  I would probably try that first.

To try an initial prototype of this could be around 6 hours.  Then we will probably want to refine it in design meeting, then it will take longer to go through code review and QA.

Would we show the "Mirror" option for Water and Sound, or only for Light?

**Comment by arouinfar** [comment]
Thanks @samreid. I do not think it is feasible to add a mirror to 1.0. 

If @kathy-phet feels strongly about its inclusion in 2.0, we should discuss this further in design meeting. While I think it's a nice parallel to Wave on a String, I do not think the mirror serves any of the primary learning goals of this sim.

**Comment by samreid** [comment]
@ariel-phet recommends to leave this feature out until there is a more compelling reason to add it.
@kathy-phet is fine with waiting, but we can re-evaluate if we get more requests for it.

@samreid points out this would complicate the "black part of the wave" propagation computation---not clear how that could be done.
