### ISSUE TITLE
The first trough is smaller than subsequent troughs.

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#308]
@arouinfar identified that the first trough is smaller than subsequent troughs.  Deferred for 2.0+

**Comment by samreid** [comment]
Note the first wavefront is smaller amplitude than following wavefronts.  This seems incorrect and nonphysical.  I'm not sure what explains it--seems to be more than the usual attenuation.

![image](https://user-images.githubusercontent.com/679486/51004578-81954880-14f8-11e9-8d1f-92354099a2b8.png)

**Comment by samreid** [comment]
This problem is significantly reduced after we increased the lattice size:

![image](https://user-images.githubusercontent.com/679486/52351085-3c751100-29e7-11e9-9444-959a42c6427f.png)

This indicates the problem is due to the discretization on the lattice.  As an experiment, I tried lattice size = 501.  The sim ran slowly but the leading wavefront had nearly the same amplitude as subsequent waves:

![image](https://user-images.githubusercontent.com/679486/52351274-aab9d380-29e7-11e9-8afc-03612ef0e152.png)

Workarounds may be possible, but this suggests the direct way to solve this is by increasing the lattice size.

@arouinfar want to close this issue?  Leave it open as deferred?  Something else?

**Comment by arouinfar** [comment]
Since the dampening of the trough is more noticeable for closely-spaced wavefronts, here's the worst-case scenario:

![image](https://user-images.githubusercontent.com/8419308/52355229-3420d400-29ef-11e9-8f0a-4cd81de14aa4.png)

Compare that to a fully propagated wave (2nd wavefront is at the right edge of lattice):

![image](https://user-images.githubusercontent.com/8419308/52355390-78ac6f80-29ef-11e9-948f-c4761de3506c.png)

While not ideal, I think the pulse shape is still reasonable. I don't see how we could increase the lattice size any further, given the performance issues that cropped up for older devices running iOS 12. 

@samreid would rendering the lattice in WebGL potentially allow us to increase the lattice resolution while preserving reasonable performance?

**Comment by samreid** [comment]
At the moment, `paintCanvas` is taking up about 18.5% of the application time (on a built version, on Mac Chrome).  Moving to WebGL would likely reduce this, but not to zero.  Would it allow us enough CPU to increase the lattice size?  Maybe a little bit.  We are already at a lattice size of 151x151 = 22801 cells. If we go to 200x200=40000 that is a 175% increase in number of cells, which will consume more CPU for both the model and the view.  

Doing a back-of-the-envelope calculation: assuming we want 15% more cells, that would be `Math.sqrt(15/100*22801+22801) = 162`, so increasing from 151x151 to 161x161 (keeping odd to have a central row and column).  I'm not convinced this will be worth the effort.

**Comment by samreid** [comment]
Reassigned to @arouinfar for discussion.  Not sure if it should also be marked for design meeting.

**Comment by arouinfar** [comment]
@samreid thanks for the assessment. I think this is something we can close as wont-fix, but would be good to get final approval from the group, so leaving tagged for design meeting.

**Comment by samreid** [comment]
@ariel-phet and @kathy-phet agree this can be closed without further investigation.
