### ISSUE TITLE
Diffracted beam representation

### ISSUE THREAD

**Issue by arouinfar** [phetsims/wave-interference#375]
The diffracted beam could use a bit of cleanup so that it looks like it hits the entire screen, with a higher saturation near the center.
![image](https://user-images.githubusercontent.com/8419308/56684073-2db80500-668c-11e9-94ff-a9635e92d161.png)

Here are some diagrams from papers which show a similar representation.
![image](https://user-images.githubusercontent.com/8419308/56684042-21cc4300-668c-11e9-9e43-9dd88e61aa8a.png)

Self-assigning for mockups.

**Comment by arouinfar** [comment]
For the diffracted beam, I drew a 2D shape which extends from the top/bottom corners of the aperture rectangle, and extends to the outer corners of the screen (outlined in magenta in first image). I then applied a linear gradient, concentrating the original beam color in the middle. Since the screen is obscured, I turned down the opacity of the entire diffracted beam (middle), but that washes out the beam too much while still leaving the screen a bit obscured. To get around that, I tried adding another gradient on top to reduce the opacity near the screen only (bottom) which seems to work well.

![image](https://user-images.githubusercontent.com/8419308/56930203-26806500-6a99-11e9-941e-5128df544d2e.png)

@ariel-phet this is the closest I could get to recreating the diagrams, and I think this is a significant improvement over the current look. Do you have any thoughts or suggestions for further tweaks?

@samreid do you think you could draw something like this in code? The only alternative I could think of would be to create an asset for a semi-transparent mask which you could then layer on top of the diffracted beam. However, I don't think it would create the same effect.

**Comment by ariel-phet** [comment]
@arouinfar mainly I would narrow the left of the shape, so it more looked like it was coming from an aperture at the center of the aperture rectangle, rather than from the whole rectangle. Basically give it a much sharper "cone" appearance at the left end. Otherwise I think the look on the diffraction screen and such is really nice.

**Comment by samreid** [comment]
> @samreid do you think you could draw something like this in code? 

Let's try rendering this in code first.  I'll take a look.

**Comment by arouinfar** [comment]
Thanks for the feedback @ariel-phet. I think having a true point at the aperture ended up looking a bit too sharp, but I do like the look of a shaper cone, generally. Is this what you were thinking?

![image](https://user-images.githubusercontent.com/8419308/56978648-39e10e00-6b35-11e9-93e7-ddfae51c01f6.png)

**Comment by ariel-phet** [comment]
@arouinfar yes, exactly what I was thinking.

I am fine with whatever cone size you feel works best.

**Comment by arouinfar** [comment]
@ariel-phet thanks!

@samreid what would be the next steps? Would it be helpful to send you artwork for this polygon?

![image](https://user-images.githubusercontent.com/8419308/56990374-2a23f280-6b52-11e9-9424-a4fe21e5eee3.png)

**Comment by samreid** [comment]
I'll take a first pass at drawing it in the code, thanks!

**Comment by samreid** [comment]
I added a rough draft of a cone and gradient.  Some notes about the implementation:

* I used a vertically symmetrical linear gradient with color stops for the opacity.  These can be changed if desired
* It looks like the beam gets weaker as it goes further to the right in https://github.com/phetsims/wave-interference/issues/375#issuecomment-488098774, I'm not sure how to implement that and that effect does not appear in this commit.  Let me know if that is an essential part, and I can reach out to other developers for ideas.
* Showing the gradient overlay in front of (by z-ordering) the mini-diffraction screen as we have done previously is physically correct, but looks awkward because of the strong central part of the beam, and obscures the mini-diffraction screen significantly.  Hence for this draft, I moved the mini-diffraction screen and aperture rectangles to the front (in z-order) so they are not obscured.
* It was difficult to find parameters that work well at every color. For instance, yellow gradients are difficult to see.

@arouinfar can you please take a look and let me know your thoughts?

**Comment by arouinfar** [comment]
@samreid overall things are looking great! My only nit-pick is that it looks like the beam is somewhat misaligned with the screen.

<img src="https://user-images.githubusercontent.com/8419308/57316828-ef6f0c80-70b3-11e9-80e6-100f420b0137.png" width=300>


> I used a vertically symmetrical linear gradient with color stops for the opacity. These can be changed if desired

Looks good!

> It looks like the beam gets weaker as it goes further to the right in #375 (comment), I'm not sure how to implement that and that effect does not appear in this commit. Let me know if that is an essential part, and I can reach out to other developers for ideas.

In Illustrator, I was able to add a horizontal opacity gradient skewed to the end of the beam which greatly reduced the opacity of the beam over the screen. I'm not sure if this is something that could reasonably be done in code, so we may just decide to layer the screen on top of the beam.

> Showing the gradient overlay in front of (by z-ordering) the mini-diffraction screen as we have done previously is physically correct, but looks awkward because of the strong central part of the beam, and obscures the mini-diffraction screen significantly. Hence for this draft, I moved the mini-diffraction screen and aperture rectangles to the front (in z-order) so they are not obscured.

![image](https://user-images.githubusercontent.com/8419308/57316454-12e58780-70b3-11e9-9410-707f8a2e0396.png)

I think the screen looks fine layered on top and may remove the need for adding the extra gradient I described above. I think the beam touching the corners of the screen creates the illusion that the beam is on top, but perhaps just hard to see. 

That said, the aperture rectangle looks really odd layered on top, so I would leave that sandwiched between the incoming and diffracted beams.

> It was difficult to find parameters that work well at every color. For instance, yellow gradients are difficult to see.

That's okay with me. I think the beam is generally meant to be iconic, and the gradient is looking good for most wavelengths.

**Comment by samreid** [comment]
> My only nit-pick is that it looks like the beam is somewhat misaligned with the screen.

I wonder if we are seeing an optical illusion?  When I turn the opacity to a constant, it seems to line up correctly:

![image](https://user-images.githubusercontent.com/679486/57328155-e55a0780-70cd-11e9-9ef0-e2ac9749ca6a.png)

Here's how 380nm light looks on my side without guards:

![image](https://user-images.githubusercontent.com/679486/57328247-27834900-70ce-11e9-8225-00aeba3f193d.png)

Assuming for the sake of discussion this is an optical illusion caused by seeing the length of the bottom of the black rectangle next to the part where the light is most faded, should we leave it as it is, or try to correct for it by adjusting the gradient stops or adjusting the geometry?

> That said, the aperture rectangle looks really odd layered on top, so I would leave that sandwiched between the incoming and diffracted beams.

Prior implementations had the light falling on the midline like so:

![image](https://user-images.githubusercontent.com/679486/57328403-92cd1b00-70ce-11e9-8597-2e12f056f7bb.png)

This obscures the aperture pattern, but also is an incorrect 2d "slice" of the incident light.  Should I change its geometry so it reaches all of the vertices of the aperture rectangle?  Note I changed the opacity of the incoming light from 0.6 to 0.7 due to constraints from the transmitted beam tweaking.

Also, should the incoming beam also have a linear gradient like the transmitted beam?  I'm thinking not but wanted to double check.

**Comment by arouinfar** [comment]
> I wonder if we are seeing an optical illusion? When I turn the opacity to a constant, it seems to line up correctly

After further inspection, I think you're right @samreid. I do think it's just an optical illusion.

> should we leave it as it is, or try to correct for it by adjusting the gradient stops or adjusting the geometry?

Let's leave it as-is, @samreid.

> This obscures the aperture pattern, but also is an incorrect 2d "slice" of the incident light. Should I change its geometry so it reaches all of the vertices of the aperture rectangle? Note I changed the opacity of the incoming light from 0.6 to 0.7 due to constraints from the transmitted beam tweaking.

I wasn't thinking about the obscured aperture, but you do raise a good point. I don't think we want to change the incident beam's geometry. Maybe it would be better to layer the aperture on top, after all.

>Also, should the incoming beam also have a linear gradient like the transmitted beam? I'm thinking not but wanted to double check.

No, I think we want that to be solid, since it's a collimated source.



@ariel-phet can you review the updated diffracted beam path and @samreid's notes in https://github.com/phetsims/wave-interference/issues/375#issuecomment-490137901?

**Comment by ariel-phet** [comment]
@samreid @arouinfar personally I think this all looks production ready to me. This representation is give the general gist in my opinion, not be absolutely perfect. I think it does a nice job of suggesting the geometry and emphasizing the central maximum. 

I think this issue can be closed

**Comment by arouinfar** [comment]
👍
