### ISSUE TITLE
Considerations for particle view of sound

### ISSUE THREAD

**Issue by arouinfar** [phetsims/wave-interference#39]
For #31 

Unfuddle Ticket [#604](https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/604)

Wendy:
> Curious thing about the particle view on sound sim.  Seems like it 
tends to pile the particles up in the regions of high intensity and 
lose them from the nodes of the wave, so as time progresses it gets 
emptier and emptier along the interference nodes. I had let it run a 
while before the screenshot and was not paying that much attention, so 
did not notice it much, until I just looked again at the image, and went back and investigated with the sim.
Don't know if this is just a curious artefact that appears. In any case, don't want 
it.

> Kathy suggests fixing this with more and smaller particles

> Wendy also noticed that the particles appear to be in a sheet the size of the box they are in. This makes it so that when they are oscillating, they leave empty areas along the sides and the ends where there are not minumums so it's quite decieving.  Seems that this can easily be fixed by increasing the size of area of the particles but leave the black box they appear in the same size. To fix the problem with minimums will take some more discussion with Noah P. and Sam

Noah P:
> Making the particle box larger than the visible pool seems like a good solution to comment 2, if easy to program.

> I was not able to reproduce the piling up of particles, after waiting about 5 minutes. How long does it take to see this? What settings (freq and amplitude) make it appear?

> When the freq is low, this problem does not appear. When freq is turned up, it creates a thin area around the edge where particles do not go. It is pretty subtle, so maybe not important. I haven't seen this be a problem with students (yet).

The apparent issues:
1. Particles tend to pile up in regions of high intensity and are lost along interference nodes
2. Particles appear to make up a sheet which can leave some empty space long the edges that do not correspond to minima. At high frequency, there is a thin area around the edge where particles do not go.

A few suggestions were made, but I don't know if any changes were made
* Decrease size of particles
* Increase size of particle box. (Java offers a small and large viewing window, and both currently exhibit the same behavior.)

At the default settings, particles oscillate outside of the viewing window.
![image](https://user-images.githubusercontent.com/8419308/38106498-65f18f0a-334c-11e8-9348-1e6e13b4e994.png)

At max frequency, there is an apparent buffer between the edges of the viewing window and the particles.
![image](https://user-images.githubusercontent.com/8419308/38106573-a3c57972-334c-11e8-829e-5f54919660aa.png)

When the waves interfere, particles do collect in regions of maxima, and are absent from the nodes. This happens almost immediately. From Wendy's comments, it seems like this may not be the desired behavior. 
![image](https://user-images.githubusercontent.com/8419308/38106705-15e4071c-334d-11e8-883e-c98739d5eaf5.png)

**Comment by arouinfar** [comment]
Summary from June 28 design meeting: 

* The particle view of sound best serves the learning goals of the Intro screen. 
* It might be nice to show it on the Interference screen, but the Java behavior is problematic. The particles pooling along the maxima creates an illusion of regions of vacuum, which is inaccurate. @samreid suggested that the model could be refined to look at wave energy, instead.
* The particle view of sound does not serve any particular learning goal on the Slits screen, so do not include it there.
* Blue-ish color makes the particles look like electrons, so use a different color. Wave is grayscale, so try white or light gray.
* X marker is heavy-handed, but a useful visual reference. Let's instead try making the particle itself red. 

@samreid here are the next steps
* Start with Intro screen only
* Devs choice UI component to switch between views
* Update colors: white/light gray particles, with "marked" particles being red 
* Clip animation so particles do not oscillate outside of the viewing window.
* Feel free to investigate model changes that produce less-problematic interference behavior, though for now, that's not the primary goal

**Comment by samreid** [comment]
I noticed in the Java simulation, if you turn off the wave and wait 20 seconds or so, the sound particles settle into a grid:

![image](https://user-images.githubusercontent.com/679486/44471962-54e4a100-a5ea-11e8-95af-c19169074a1a.png)

This seems undesirable.  First, we should randomly position the particles and second, we should have random motion even when there is no wave (since we are not at absolute zero).

**Comment by samreid** [comment]
I have a rough draft of sound particles working.  It uses two checkboxes which are grayed out for water and light, and only respected for sound.  I placed them above the "Screen" checkbox because that is light-specific.  I wasn't sure whether they should go above or below "Graph".  Some known issues:

- [ ] sound particles wave crests aren't clear at higher frequencies.  You can see this by turning on both "waves" and "particles" and turning up the frequency past halfway
- [ ] I haven't checked performance on iPad 2
- [ ] I recommend showing some slight random motion even there is no wave, since we are not at absolute zero.

I noted that the new HTML5 particle model does not exhibit the same incorrect behavior as the Java version with respect to particles vacating the nodes.

![sounds](https://user-images.githubusercontent.com/679486/44505166-150ad180-a65d-11e8-9cff-02ab64de2465.gif)

I also decided to leave this option available for all screens for consistency and because it looks great for the plane waves and single slit.

@arouinfar can you please review this on phettest and let me know if you have other recommendations?

**Comment by samreid** [comment]
> sound particles wave crests aren't clear at higher frequencies. You can see this by turning on both "waves" and "particles" and turning up the frequency past halfway

This problem is equivalent or worse in the Java version.  Some options for addressing it in HTML5: 

a) The particle physics model has about 8 free parameters that I tinkered with to get it where it is now.  It's possible that with more tinkering, we could get the particles to be more responsive to higher frequencies.
b) We could reduce the range of frequencies

**Comment by samreid** [comment]
> I recommend showing some slight random motion even there is no wave, since we are not at absolute zero.

That seems separate, I'll create another issue for that part.

**Comment by arouinfar** [comment]
@samreid the particle view is looking really nice! As discussed in design meeting, the team likes the combination of the wave and particle views.

> I recommend showing some slight random motion even there is no wave, since we are not at absolute zero.

Agreed! Thanks for opening the issue.

> We could reduce the range of frequencies.

I think part of the problem with the high frequency is that the wavefronts are too densely packed. If we reduce the range of frequencies to A3-A5, we would also need to rescale this scene a bit. In #80  I recommended the following:


>I think a range of A3-A6 could have some scaling issues at the extremes. A range of A3-A5 (880 Hz, 39.2 cm) would allow for quadrupling f, but is easier to deal with scale-wise. I would recommend a wave area of 500 cm, with a scale bar of 50 cm.

I’m going to tag this for next week’s design meeting.

**Comment by samreid** [comment]
Meeting consensus: Reach out to Martin or Mike about the physics--to see if the proposed model is reasonable.  We decided this looks good at the sweet spot but would like to get better behavior at low and high frequency.

**Comment by samreid** [comment]
Draft email here, I'll send it to Martin and Mike:

We could use your help developing the physical model for the motion of sound particles in wave propagation.  We would like to have a dynamical version that looks something like this animated gif:
https://www.npr.org/assets/img/2014/04/08/compressionwave.gif

You can see my latest attempt here, by clicking on "Waves" then the Speaker icon, then "Particles":
https://phet-dev.colorado.edu/html/wave-interference/1.0.0-dev.26/phet/wave-interference_en_phet.html

To summarize the proposed algorithm in pseudocode:
For each particle, I iterate over a neighborhood of points in the wave lattice.  Each point in the neighborhood contributed a term to the sum of forces on the particle.  Wave crests attract, wave troughs repel.  The magnitude of each force term is proportional to the magnitude of the wave value in that cell (not a function of the distance to the cell).  There is also a random force applied at each time step, to add random motion.  And the particle feels a spring force (F=-kx) towards its original location so that particles won't drift from their home.

Here's the full code for the algorithm I developed, in case it makes things more clear.
```js
for ( let soundParticle of this.soundParticles ) {

  // Check the lattice coordinate of the current location of the particle
  const latticeCoordinate = this.modelToLatticeTransform.modelToViewXY( soundParticle.x, soundParticle.y );

  // feel a force toward each lattice value in a local neighborhood
  let sumFx = 0;
  let sumFy = 0;
  const SEARCH_RADIUS = 3;
  const CLAMPED_WAVE_VALUE = 1;

  for ( let i = -SEARCH_RADIUS; i <= SEARCH_RADIUS; i++ ) {
    for ( let k = -SEARCH_RADIUS; k <= SEARCH_RADIUS; k++ ) {
      const neighborI = Math.round( latticeCoordinate.x ) + i;
      const neighborJ = Math.round( latticeCoordinate.y ) + k;
      if ( lattice.contains( neighborI, neighborJ ) ) {
        let waveValue = lattice.getCurrentValue( neighborI, neighborJ );
        if ( waveValue > CLAMPED_WAVE_VALUE ) {
          waveValue = CLAMPED_WAVE_VALUE;
        }
        else if ( waveValue < -CLAMPED_WAVE_VALUE ) {
          waveValue = -CLAMPED_WAVE_VALUE;
        }
        const springConstant = waveValue / SEARCH_RADIUS / SEARCH_RADIUS * 2.8; // Tuned manually
        const forceCenter = this.modelToLatticeTransform.viewToModelXY( neighborI, neighborJ );

        // Normalize out the distance so that further away points don't contribute more just from being further away
        const fAirX = -springConstant * ( soundParticle.x - forceCenter.x ) / Math.abs( soundParticle.x - forceCenter.x );
        const fAirY = -springConstant * ( soundParticle.y - forceCenter.y ) / Math.abs( soundParticle.y - forceCenter.y );
        sumFx += fAirX;
        sumFy += fAirY;
      }
    }
  }
  soundParticle.applyForce( sumFx, sumFy, dt );
}
```

together with 

```js
applyForce( fx, fy, dt ) {

  // the particles move randomly even when there are no waves, because they are not at absolute zero
  // see https://github.com/phetsims/wave-interference/issues/123
  const RANDOM_MAGNITUDE = 3;
  fx += ( Math.random() - 0.5 ) * 2 * RANDOM_MAGNITUDE;
  fy += ( Math.random() - 0.5 ) * 2 * RANDOM_MAGNITUDE;

  // use the airK as the magnitude and the forceCenter for direction only.
  const RESTORATION_SPRING_CONSTANT = 3;
  const fSpringX = -RESTORATION_SPRING_CONSTANT * ( this.x - this.initialX );
  const fSpringY = -RESTORATION_SPRING_CONSTANT * ( this.y - this.initialY );
  this.vx += fx + fSpringX;
  this.vy += fy + fSpringY;

  // friction
  this.vx *= 0.96;
  this.vy *= 0.96;

  // motion
  this.x += this.vx * dt;
  this.y += this.vy * dt;
}
```

What we are seeing in the https://phet-dev.colorado.edu/html/wave-interference/1.0.0-dev.26/phet/wave-interference_en_phet.html link is pretty good behavior around the default frequency values, but when the frequency is turned up high, the particles can't keep up with the waves (so it shows twice of the desired wavelength).  And with the frequency low the wave crests are no longer apparent.

Does this seem like a reasonable physical model for the sound particle motion?  How would you change it to get better behavior at the high and low frequencies?

**Comment by samreid** [comment]
I emailed Martin and Mike, on hold until I hear back.

**Comment by samreid** [comment]
Mike and I were trying this out:

```js
        var x = soundParticle.x;
        var y = soundParticle.y;
        var r = Math.sqrt( x * x + y * y );

        const a = 2 / Math.sqrt( r );
        const frequency = model.soundScene.frequencyProperty.value;
        const wavelength = 34 / frequency;
        const angularFrequency = Math.PI * 2 * frequency;
        sumFx = a * Math.sin( 2 * Math.PI * r / wavelength - angularFrequency * model.timeProperty.value ) * x;
        sumFy = a * Math.sin( 2 * Math.PI * r / wavelength - angularFrequency * model.timeProperty.value ) * y;
        soundParticle.applyForce( sumFx, sumFy, dt );
```

**Comment by samreid** [comment]
I implemented the gradient pressure force that Mike and & I discussed today.  It is simpler and less computationally expensive, and looks great.  Turning down the randomness and turning up the friction gives very clear waves at the default frequency.  At low frequency, it is still difficult to see the broad waves. I tried increasing the coefficient at low frequencies, but it had erratic behavior near the oscillator.  At high frequency, the gradient pressure force has the same problem as the prior algorithm, that the particles can't keep up with the high frequency, and end up catching every other wave crest.  Not sure if changing the coefficient would help here or not.

**Comment by arouinfar** [comment]
A frequency range of A4-A5 corresponds to 440 Hz to 880 Hz, which still allows for doubling f. That range is a little narrower than I would have liked, but I think it's an acceptable trade-off. Speaking with @kathy-phet she would also agree.

@samreid not sure if Mike will be available, but I will likely have some time to discuss parameter tuning after dev meeting tomorrow.

**Comment by samreid** [comment]
We decided we would like to add controls for the free parameters so we can determine what's best.  I'll do so.

**Comment by samreid** [comment]
Controls being added in https://github.com/phetsims/wave-interference/issues/157

**Comment by samreid** [comment]
We'll address tuning in #158, on hold until that's complete.

**Comment by samreid** [comment]
Tuning in #158 is complete, @arouinfar can this issue be closed?

**Comment by arouinfar** [comment]
It sure can @samreid!
