### ISSUE TITLE
Multi-color patterns 

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/wave-interference#403]
**Test device:**
Dell
**Operating System:**
Win 10
**Browser:**
chrome
**Problem description:**
For https://github.com/phetsims/QA/issues/322.  Not applicable to published version.
On the diffraction screen, certain colors will have a different color in the center of the pattern.  This happens throughout the slider during color transitions, but is most noticeable when light is orange (center looks yellow).  I can't think of a physical reason why the color of the light would be changing.  @arouinfar thought it might be due to code controlling the brightness.
**Steps to reproduce:**
1. Go to the 4th screen
2. Turn on the light beam
3. Adjust the slider slowly towards orange

**Screenshots:**
![differentcolors](https://user-images.githubusercontent.com/41024075/58359668-da2f0780-7e41-11e9-8691-91d6b4babcce.png)

Troubleshooting information (do not edit):

<details>

Name: ‪Wave Interference‬
URL: https://phet-dev.colorado.edu/html/wave-interference/2.0.0-dev.1/phet/wave-interference_en_phet.html
Version: 2.0.0-dev.1 2019-05-24 04:17:12 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by arouinfar** [comment]
Here are a few more examples showing some pretty obvious multi-colored patterns.
![Wave Interference screenshot (1)](https://user-images.githubusercontent.com/8419308/58359752-4873ca00-7e42-11e9-852e-08b3512eb8fd.png)
![Wave Interference screenshot (2)](https://user-images.githubusercontent.com/8419308/58359753-4873ca00-7e42-11e9-8e55-43fe00b440a8.png)
![Wave Interference screenshot](https://user-images.githubusercontent.com/8419308/58359754-4873ca00-7e42-11e9-8e09-eb0da68d9cbe.png)

Checking 1.1.0-dev.1 through dev.5, the behavior seems like it's always been present. However, this looks really strange to me, and I'm not quite sure why the central maximum would have a different color.

**Comment by ariel-phet** [comment]
@arouinfar @KatieWoe I am pretty sure this is merely a "perceptual" effect... we are saturating some of the RGB values (when I inspect with a color picker), and our eye does not have a linear response to intensity. Especially because of the way RGB represents color, I am guessing this is just an unavoidable side-effect of getting some sort of saturated intensity in certain places. 

@samreid any insight here?

**Comment by samreid** [comment]
The values in the FFT matrix are between 0-1.  These values are scaled by the `baseColor` which is chosen in the wavelength slider.  Then there is an additional scale factor which is currently defined like so:

```js
  // Linear scaling factor to increase the brightness
  const SCALE_FACTOR = 3;
```

This confirms @ariel-phet's suspicion that we are saturating some values near the origin.  For example, imagine that a base color is rgb = (20, 240, 40).  i.e. mostly green.  Then when scale by a factor of 3 and clamp we have (60, 255, 120) which is a different shade (closer to white).

I wonder if we can stop scaling once any channel hits 255?  Could that lead to inconsistent behavior? 
 Or we could turn down the scale factor, but that would make it harder to see ripples further from the origin.  For example, here is scale factor = 1

![image](https://user-images.githubusercontent.com/679486/58583648-b6890a00-8211-11e9-98e5-2855bf12cd2a.png)

and here is scale factor =2.

![image](https://user-images.githubusercontent.com/679486/58583697-d6203280-8211-11e9-99bb-24dea66c40af.png)

here is scale factor = 3

![image](https://user-images.githubusercontent.com/679486/58583743-ea642f80-8211-11e9-9303-9a4d944b43a8.png)

@arouinfar or @ariel-phet what do you recommend?

**Comment by ariel-phet** [comment]
@samreid can you make a query parameter for the scale factor so I can try a few different ones and play with the sim?

That being said (and I think worth optimizing) @samreid @arouinfar due to the way the eye perceives color (nonlinear, dependent on color, and saturation effects) I am not sure we have to worry about this effect all that much. I agree it would be nice to keep things monochromatic, so I think tuning the scale factor is appropriate, but if we cannot reduce all cases, I think I am OK with that. For instance, here are some pics of actual airy patterns from monochromatic sources that look multicolored because of saturation effects creating a "white" look to the center

![airy](https://user-images.githubusercontent.com/4051174/58604959-7d718980-8253-11e9-8a6e-22e41f68dfc2.jpg)
![airy_disk](https://user-images.githubusercontent.com/4051174/58604972-84000100-8253-11e9-9ea4-b9a9cdd45c15.png)

**Comment by samreid** [comment]
Here is a dev version that you can specify a different scale factor with a query parameter:

https://phet-dev.colorado.edu/html/wave-interference/2.0.0-dev.2/phet/wave-interference_en_phet.html?diffractionScaleFactor=3.0

**Comment by ariel-phet** [comment]
@samreid please change the scale factor to 2.5, that seems to keep the colors fairly consistent, you will still get the "bright effect" in the center to some extent but it is not as prominent.

@arouinfar we probably want to add a note to the teacher tips that the diffraction pattern is always monochromatic but due to saturation effects might look like a slightly different color in the center.

**Comment by samreid** [comment]
Brightness changed, leaving assigned to @arouinfar to update the teacher tips.  @arouinfar once that's complete, this issue can be closed.

**Comment by arouinfar** [comment]
@ariel-phet @samreid I think the `diffractionScaleFactor=2.5` looks good. It maintains a reasonable brightness while minimizing the apparent multi-colored patterns.

I'll track teacher tips separately in #410. Closing.
