### ISSUE TITLE
Waves Intro code review

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#414]
@kathy-phet requested a code review for the changes that allowed us to adapt Wave Interference into Waves Intro, where each scene is split up into a separate screen.  The two files that were introduced to support this change are `BasicScreen.js` and `MediumScreen.js`.  I'll self-assign at first to make sure they are ready for review.

**Comment by samreid** [comment]
@pixelzoom can you please review these two files at your convenience?  It's less than 100 lines of code and I believe we are hoping to get this published for the beginning of school in the fall.

**Comment by pixelzoom** [comment]
I just did pull-all.sh to review https://github.com/phetsims/wave-interference/issues/414#issuecomment-511940094.  Waves Intro starts up OK. But Wave Interference is failing at startup:

```
assert.js:22 Uncaught Error: Assertion failed: initial scene should be specified
   at window.assertions.assertFunction (assert.js:22)
   at new BasicScreen (BasicScreen.js:36)
   at new WavesScreen (WavesScreen.js:32)
   at wave-interference-main.js:50
   at Namespace.window.phet.joist.launchSimulation (SimLauncher.js:50)
   at doneLoadingImages (SimLauncher.js:71)
   at Object.launch (SimLauncher.js:125)
   at wave-interference-main.js:39
   at Object.execCb (require-2.3.6.js:1696)
   at Module.check (require-2.3.6.js:883)
```

Back to @samreid to fix before I continue review.

**Comment by pixelzoom** [comment]
While you're fixing... 

If I understand the doc for `MediumScreen`, each screen in Waves Intro is creating all scenes, but only showing one scene.   This seems incredibility wasteful, not to mention problematic for PhET-iO.  You need 3 scene instances, but you're creating 9 scenes (3 screens x 3 scenes) and ignoring 6 of them.  Something that takes a list of scenes would be more general and flexible.   Provide all 3 scenes for WavesScreen, provide only the 1 desired scene for each Screen in Waves Intro. 

Also recommended to rename `BasicScreen` to `BaseScreen`, as it is described as "Base class for WavesScreen and MediumScreen".

**Comment by samreid** [comment]
I reverted the incorrect assertion but will need to take a closer at the options and the preceding comment after lunch.

**Comment by samreid** [comment]
I renamed BasicScreen => BaseScreen and switched to a pattern that only creates components for the specified screens.  @pixelzoom can you please review?

**Comment by arouinfar** [comment]
> @arouinfar can you please test on phettest after these changes, testing in particular to verify that nothing is broken with respect to (a) layering and (b) making sure that each scene has the appropriate features?

@samreid nothing appears to have been disturbed.

**Comment by arouinfar** [comment]
@samreid actually I have to walk that back. The `ResetAllButton` is broken. When pressed, it gets stuck like this, and requires a browser refresh.
![image](https://user-images.githubusercontent.com/8419308/61972332-8e622100-af9e-11e9-9f3b-848b6c892060.png)

**Comment by samreid** [comment]
Thanks @arouinfar, I fixed the reset problem.  Can you please re-test?

**Comment by arouinfar** [comment]
The `ResetAllButton` is now working in master. Thanks @samreid.

**Comment by pixelzoom** [comment]
Review is completed.

Overall:

- [ ] While I don't like the number of tests for the existence of scenes that this solution requires (e.g. `if ( model.waterScene )`), I understand how you got here, and it seems like a justifiable compromise.   Recommended to say something about this in either WaveModel.js or implementation-notes.js -- noting what you're doing and why.

Specific issues:

- [ ] Screen names are not localized. They currently appear as string literals in waves-intro-main.js (e.g. `name: 'Water'`), and need to be moved to waves-intro-strings_en.json.

- [ ] The API for Array `indexOf` is documented as "-1 if not found".   Tests like this one in WaveModel.js should be changed accordingly:  
```js
-  if ( options.scenes.indexOf( 'waterScene' ) >= 0 )
+  if ( options.scenes.indexOf( 'waterScene' ) === -1 )
```

- [ ] wave-interference/js/medium/ directory violates PhET directory structure conventions. There is no "medium" screen.  Recommended to move MediumScreen.js to either wave-interference/js/common/ or waves-intro/js/common/.  The latter may be more appropriate, since MediumScreen.js is only used in waves-intro, but I also understand the desire to keep all code in wave-interference.

**Comment by samreid** [comment]
Thanks for the review, I addressed the points raised in the preceding comment.  @pixelzoom can you please re-review?  Close if all is well.

**Comment by pixelzoom** [comment]
I reviewed commits, looks good.  Closing.
