### ISSUE TITLE
Units for Sound scene

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#42]
In the Java version, the sound wave tank measures 100cm and the default wavelength is 52cm = E5 (the E above concert A).  However, on the lattice this wavelength makes it very difficult to see interference:

![image](https://user-images.githubusercontent.com/679486/39459743-f7b0ee72-4cba-11e8-928d-dec7ccc4f8d6.png)

But it is easy to see the particle behavior:

![image](https://user-images.githubusercontent.com/679486/39459785-34861318-4cbb-11e8-965f-68af2a4456bd.png)

The maximum frequency has a wavelength of 8.15cm which is around C8 (4 octaves above middle c), and it is easy to see interference at this frequency:
![image](https://user-images.githubusercontent.com/679486/39459733-e43538a8-4cba-11e8-9e95-dcdcf3c3b80c.png)

And the particles settle into this pattern:
![image](https://user-images.githubusercontent.com/679486/39459808-56e408e8-4cbb-11e8-943c-e505ac3d5bbe.png)

Do we want to stick with similar values for the HTML5 version?  Or choose a less arbitrary initial frequency, such as concert A (440 Hz)?  Do we want large waves that don't show interference, but show broad waves for the particle view?  So far, in the HTML5 version, the initial frequency is the middle of the range, but in the Java version, it is some 20% up for the frequency range for water and sound (about 60% to the right for light).  How should we design this for the HTML5 version?

**Comment by arouinfar** [comment]
@samreid I think it's important to have a large range of frequencies, but the minimum should probably be something we can hear -- such as A0 (27.5 Hz) -- not the 0.5 Hz minimum we talked about in April 12th design meeting. (However, 0.5 Hz would still be an appropriate minimum for water.)

Since sound isn't the default scene, and the scenes are synchronized, the question of the default frequency is a bit moot. We could choose something the 440 Hz (slider thumb ~10%), but chances are the users will move the slider in the water scene before getting to sound.

**Comment by samreid** [comment]
After using the simulation, I no longer believe we should match frequencies across scenes.  For instance, it seems odd that putting water at 0.5 Hz would automatically change the light color to 780nm.  Likewise, if we allow each scene to have its own independent frequency, we can control the initial value they will see for sound (perhaps 440Hz) and for light (perhaps the same red shade as in the Java version, which was 660nm.) The way we are designing it, the minimum frequency for water and the minimum frequency for light will not look the same on the lattice anyways, and I don't think it makes sense to couple them.

**Comment by samreid** [comment]
Sorry, I hit close by mistake.  I'm interested to hear your thoughts on the preceding comment.

**Comment by arouinfar** [comment]
In the [05/17/18 design meeting](https://docs.google.com/document/d/1Lr5A7LG8PyrTHD5tC0Ux4IP9nF7XrE-bZTyRIc7Yc2A/edit#heading=h.vglux3rqyign) we decided that the frequency slider should be independent across the scenes. This will allow for us to choose thoughtful defaults, and the changing frequency will be another cue to students that something has changed between scenes.

**Comment by arouinfar** [comment]
Reassigning to @samreid in case any additional work needs to be done.

**Comment by samreid** [comment]
Currently the lattice area is 100cm and the default wavelength is A4 at 440Hz and 78.41cm, so it's 3/4 across the wave area, like this:

![image](https://user-images.githubusercontent.com/679486/43004301-92dceafc-8bec-11e8-88a8-cebdd41bf3e4.png)

It will be impossible to show any interference at this scale on the lattice.  We will either need to choose a larger width for the wave area, or a higher frequency for the sound.  Also, the Java sim emits audible sound, but we haven't discussed this for HTML5 yet.  This will constrain what pitches we will want to use.  I'll open another issue for that part.

**Comment by samreid** [comment]
I'm working on this issue now because it pertains to #73

**Comment by samreid** [comment]
I updated the lattice width to be 200cm across, with a frequency range of:

minimumFrequency: 220 / 1000, // A3 in cycles per ms, wavelength is 156.82cm
maximumFrequency: 1760 / 1000, // A6 in cycles per ms, wavelength is 19.60cm

@arouinfar can you please review on phettest?  Do these ranges seem reasonable?

**Comment by arouinfar** [comment]
@samreid in https://github.com/phetsims/wave-interference/issues/80#issuecomment-406742639 I had recommended:

> I think a range of A3-A6 could have some scaling issues at the extremes. A range of A3-A5 (880 Hz, 39.2 cm) would allow for quadrupling f, but is easier to deal with scale-wise. I would recommend a wave area of 500 cm, with a scale bar of 50 cm.

The current implementation/scaling has an A3 that is rather large, and I wonder if it's too big to be productive.

![image](https://user-images.githubusercontent.com/8419308/43790272-55182dde-9a2f-11e8-9ab8-bb484e148eb5.png)

![image](https://user-images.githubusercontent.com/8419308/43790221-2fd5ce28-9a2f-11e8-9a11-f9ebf69e8f65.png)

![image](https://user-images.githubusercontent.com/8419308/43790433-d24334c0-9a2f-11e8-852e-1a88499a5b3d.png)

Let's discuss at design meeting and see what the team thinks. If the consensus is to avoid overly large wavelengths (in terms of percentage of the viewing window), then we should probably go with my recommendation above. Otherwise, the frequency ranges/scale can remain as-is.

**Comment by samreid** [comment]
We agreed the current ranges look OK.  We will have an opportunity to revisit during sonification, in #80, closing.
