### ISSUE TITLE
Light screen behavior has changed

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/wave-interference#421]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/389 (both sims)
I noticed that the screen on the light scenes seems to behave differently than in the published version.  The screen gets much brighter, and takes longer to go dark when the light stops.  It also looks a bit odd as it goes dark.  If this is the new intended behavior, please close.

**Visuals**
Old behavior
https://drive.google.com/file/d/1ayu1VQbY85iivcCTmZhqcZV6TqpNghtS/view?usp=sharing
New behavior
https://drive.google.com/file/d/1l_Zq1hiueCQ3TIq0DptV56EmLl6gcPSj/view?usp=sharing
Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Waves Intro‬
URL: https://phet-dev.colorado.edu/html/waves-intro/1.0.0-dev.10/phet/waves-intro_en_phet.html
Version: 1.0.0-dev.10 2019-07-30 22:20:16 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by samreid** [comment]
I believe we intentionally changed the behavior as part of https://github.com/phetsims/wave-interference/issues/349, but I'll leave it open to see if @arouinfar concurs.

**Comment by arouinfar** [comment]
I believe the brighter screen was an intentional part of #349, but the decay time is pretty lengthy and seems unintentional to me. Can you look into it @samreid? 

I remember at one of our more recent design meetings, @kathy-phet also mentioned the decay time as a general concern, perhaps because it was unintentionally lengthened?

**Comment by samreid** [comment]
In https://github.com/phetsims/wave-interference/issues/208 we settled on a history length of 90. Then when we increased the lattice size in https://github.com/phetsims/wave-interference/issues/315 we scaled it up by a factor of `CALIBRATION_SCALE = 1.82` because we had to run the clock that much faster to get the same wave speed (due to the larger lattice).  @arouinfar can you please review those issues and recommend how to proceed?

**Comment by arouinfar** [comment]
@samreid I don't think the calibration scale should be applied to the history length. Can you decouple them, and restore the history length to 90?

**Comment by samreid** [comment]
Done in the commit, @arouinfar can you please review on phettest and close if all is well?

**Comment by arouinfar** [comment]
@samreid thanks, the decay time is now the same between master & latest, but the decay itself looks a bit different.

These gifs show the time it takes from turning off the source to the screen going black. Both cases take the same amount of time (within experimental error).  In master the decay appears more suddenly, and is more gradual in latest. Mostly likely, this is related to changes in boosting the screen brightness, and may be unavoidable. If that's so, feel free to leave as-is @samreid. However, if there is some straightforward/low-cost way of making the fade more gradual like it is in latest, it might be worth tackling.


### Master
![master](https://user-images.githubusercontent.com/8419308/62742854-6d1d1e00-b9fd-11e9-9cc1-0873ae804bd7.gif)

### Latest Published
![latest](https://user-images.githubusercontent.com/8419308/62742920-b2415000-b9fd-11e9-8ad9-5953b73e9665.gif)

**Comment by samreid** [comment]
I tested 3 factors to see which contributed to this change:

1. The TemporalMask which drops the values to 0 instead of leaving them noisy
2. The larger averaging window used in Waves screen and Waves Intro, described here https://github.com/phetsims/wave-interference/issues/349#issuecomment-480038776
3. The nonlinear function that maps intensity to brightness, which is described in https://github.com/phetsims/wave-interference/issues/349#issuecomment-480413963 and below

I found the primary or only factor in this delayed dropoff is (3) the nonlinear function that maps intensity to brightness.  When I removed the nonlinearity and adjusted the brightness by 2x, the decay happens gradually.  With the nonlinearity, the decay happens suddenly because the nonlinearity is shaped like so:

![image](https://user-images.githubusercontent.com/679486/62779267-f1a88480-ba6f-11e9-9628-819135c3ad29.png)

That is, a gradual decrease in intensity leads to a sudden drop in brightness around intensity=0.5.  However, when I remove the nonlinearity, all of the problems described in https://github.com/phetsims/wave-interference/issues/349#issuecomment-480413963 and below return.

@ariel-phet or @arouinfar can you please advise how to proceed?

**Comment by samreid** [comment]
Also, one more follow-up question--I noted the intensity point at intensity = 0.13, brightess = 0.7 looks a little low.  I recommend bumping that up to 0.74 to round out the curve like so:

![image](https://user-images.githubusercontent.com/679486/62779516-af337780-ba70-11e9-8baf-40f241dea8a5.png)

@ariel-phet or @arouinfar sound OK?

**Comment by ariel-phet** [comment]
@samreid that sounds like a good strategy to try.

**Comment by samreid** [comment]
> @samreid that sounds like a good strategy to try.

Which strategy are you referring to?

**Comment by arouinfar** [comment]
> I found the primary or only factor in this delayed dropoff is (3) the nonlinear function that maps intensity to brightness. When I removed the nonlinearity and adjusted the brightness by 2x, the decay happens gradually. With the nonlinearity, the decay happens suddenly because the nonlinearity is shaped like so:

Ah, thanks for investigating @samreid. The non-linearity was pretty essential in reducing the appearance of interference patterns in the screen for a single source. I think the decay behavior in https://github.com/phetsims/wave-interference/issues/421#issuecomment-519718479 is an acceptable trade-off. I certainly don't love it, but I dislike it a whole lot less than single-source interference patterns.

**Comment by ariel-phet** [comment]
@samreid you asked in https://github.com/phetsims/wave-interference/issues/421#issuecomment-519903944 if:

> I recommend bumping that up to 0.74 to round out the curve like so (if we are sticking with the nonlinear function):

sounded OK, I was saying that seems worth trying.

**Comment by samreid** [comment]
Thanks, I rounded out the brightness vs intensity curve as described above.  The change is subtle and may be difficult to identify during testing.  I tested the behavior described in the top comment and it is basically the same. 

It seems there is nothing left to do for this issue.  Tagging @KatieWoe so she is aware of our (a) our decision to keep this behavior described in https://github.com/phetsims/wave-interference/issues/421#issuecomment-520285200 and (b) the minor change in the curve described in https://github.com/phetsims/wave-interference/issues/421#issuecomment-519903944.
