### ISSUE TITLE
CT testing not finishing

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/wave-interference#491]
In Wave Interference and Wave Intro a portion of the automated tests seem like they aren't being done.
![notdone](https://user-images.githubusercontent.com/41024075/76659552-595e0b00-653c-11ea-8c9b-680b837da2e2.png)
![notdoneintro](https://user-images.githubusercontent.com/41024075/76659553-59f6a180-653c-11ea-9215-231ed10772d4.png)

**Comment by jonathanolson** [comment]
It's a sim-specific failure, the import `import buttonSound from '../../../sounds/squishier-button-007_mp3.js';` in WaveGeneratorNode (in wave-interference) doesn't seem to point to anything that I see existing.

For some reason... the build is failing, but not returning an error code. Investigating that (which is why this wasn't a "loud" failure)

**Comment by jonathanolson** [comment]
Committed a change to make sure these fail loudly. Unassigning myself.

**Comment by samreid** [comment]
Thanks @jonathanolson!

**Comment by samreid** [comment]
Tests are finishing now, closing.
