### ISSUE TITLE
Disable Play Tone checkbox when sound is muted from the navbar

### ISSUE THREAD

**Issue by arouinfar** [phetsims/wave-interference#507]
When muting sound from the navbar, it turns off ALL sound in the sim. This can lead to an odd UX with the Play Tone checkbox. It's possible to interact with the checkbox, but nothing will happen. This feels really broken to me. 

@samreid would it be possible to set the `enabledProperty` of the Play Tone checkbox to false if the sound is muted? I realize this is still not a perfect solution because the checkbox could be checked, but otherwise look disabled. However, I think disabling it would still cue users that the feature isn't available.

**Comment by samreid** [comment]
I moved this issue to "wave-interference" repo since that's where the code is and so we can associate it with the milestone.

**Comment by emily-phet** [comment]
@arouinfar Just a thought - I'll defer to your decision on this. 

I agree that having the Play Tone checkbox checked + global sound disabled (=Play Tone sound not perceivable) does not visually cue why the enabled feature does not result in sound (or anything). Totally agree.

With that noted, this is behavior of every other instance in a web browser when something should be playing sound. For example, video players, browser-based games, etc.
As a general solution across sims, we may not be able to - in all cases - make something that toggles a sound appear disabled. So the solution you're in the process of implementing may not generalize beyond cases where there is a single sound-enabling checkbox (or something very similar) in the sim. 
For the long-term use of sound in sims, it would be simplest, and consistent with all other basic webpage interfaces, that global sound off is not visually cued beyond the appearance of the global sound button.

If you proceed as planned, which I'm guessing you will (and that's fine, not trying to pressure!), I just want to be clear we should not consider this decision to be generalizable beyond basic checkboxes and similar going forward. I'd prefer to avoid situations where we're spending considerable effort to figure out how to visually disable things that are more complex than a checkbox, and doing so because we think this is a requirement since we set the precedent that we cue global sound off visually.

**Comment by samreid** [comment]
I added notes to describe the detail in https://github.com/phetsims/wave-interference/issues/507#issuecomment-726936679.    @arouinfar can you please review the preceding comment and recommend how to proceed (a) for Waves Intro and (b) in general?  If Waves Intro is good with respect to this issue, let's close it.  If more discussion is warranted, perhaps it could be moved to the sonification repo?

**Comment by arouinfar** [comment]
> I  just want to be clear we should not consider this decision to be generalizable beyond basic checkboxes and similar going forward. I'd prefer to avoid situations where we're spending considerable effort to figure out how to visually disable things that are more complex than a checkbox, and doing so because we think this is a requirement since we set the precedent that we cue global sound off visually.

I completely agree @emily-phet. I think the case we're considering here is pretty narrow, and I don't think it's a pattern we can or should generalize more broadly. There is a sound in these sims (literal sine wave sound) that we want users to be able to opt-out of separately from the rest of the other sounds, and it's done with a simple UI element. 

@samreid we can proceed as planned for Waves Intro. 

I don't see the decisions we're making here to be a global pattern, and I think any further discussion would be hypothetical. I think we can go ahead and close this issue, but thanks for your thoughts @emily-phet!
