### ISSUE TITLE
Add speaker image

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#52]
On/off button should be on/near it, and it should oscillate at the appropriate frequency.

**Comment by arouinfar** [comment]
In Java, the speaker membrane appears to be a separate image that is translated back and forth. This looks a bit odd at the min/max because the edges are a bit misaligned and the gradient doesn't really match up. An advantage of sliding a single image back forth is that it is easy to map the amplitude slider.

![image](https://user-images.githubusercontent.com/8419308/40744460-cc6277cc-6411-11e8-89da-752fb8ecf944.png) ![image](https://user-images.githubusercontent.com/8419308/40744484-dfa9f1e8-6411-11e8-9117-2fe77329867a.png)

In general, there are two approaches we could take in HTML5.

1. Slide a single image back and forth, as in Java
2. Use a series of images to depict the moving membrane

| Single Image  | Series of images |
| ------------- | ------------- |
| Matches Java, so possibly easier to implement  | Could be more technically difficult to implement (not sure) |
| Naturally handles a continuous amplitude | Images would need to map to major tick marks |
| Less artwork needed  | Series of 21 images necessary if mapping to major tick marks (2 for each non-zero tick + 1 for zero-point).  |
| Some misalignment of the membrane edges   | Looks cleaner overall  |

I would be in favor of using a series of images, because it will look much cleaner. However, I am not sure if there would be any implementation challenges that would make the single image preferable.

**Comment by samreid** [comment]
The implementation as a series of images will be fine.  The main consideration will be file size--if we have 21 images or so, we will want to keep the individual file size small so the sim doesn't get too large.

**Comment by arouinfar** [comment]
@samreid I think we can keep the file size pretty small. As a test, I exported two lasers stacked on one another (since the speaker will be a bit taller) at double the necessary resolution. The .png was only 12 KB, which seems reasonably small to me.

![wave interference 3-02](https://user-images.githubusercontent.com/8419308/40794654-0680d628-64bd-11e8-943f-af6ab966e062.png)

Let's proceed with the series of images. If 21 images (10 steps) turns out to be too many, we can map the amplitude slider to fewer steps.

**Comment by samreid** [comment]
The artwork task is https://github.com/phetsims/tasks/issues/939

**Comment by samreid** [comment]
I just used a snapshot of a single image for viewing in context.  This week's meeting notes say:

> Not all membrane positions have been mocked up, but SR may instead implement the membrane in code, so artwork may not be necessary. AR will check with SR.

Using snapshot images from the AI file would allow us to get a high level of detail (including shadowing), but would either take around 13KB per file or have a more granular resolution.  I don't know how many images we would need to have it look smooth.  Perhaps 20?  If so, that would add 260KB to the simulation, or around 15%.  If we animate it within the simulation, we would split it into a background node + a foreground node which would remain static, together with the membrane node which would be stretched in code.

I'm leaning toward requesting the foreground+background+membrane images to try out, but thought I'd discuss with @arouinfar first--what do you think?

**Comment by arouinfar** [comment]
@samreid I agree that we'd need some level of detail for the membrane to make it look realistic, which would likely be easier/more compact with artwork. The speaker asset is already split into the foreground+membrane+background. I'll ask the artist to create the full series of membrane images (21 in total: 10 pairs corresponding to each non-zero tick mark on the slider, and one for the zero point).

**Comment by samreid** [comment]
@arouinfar what's the status of this issue?

**Comment by arouinfar** [comment]
@samreid the graphic artist is wrapping up some higher-priority artwork for EFAC. Wave Interference is next up in her queue.

**Comment by arouinfar** [comment]
@samreid the speaker assets are ready for implementation. I've temporarily stored them on Drive, and will delete once they've been checked in:
https://drive.google.com/drive/u/0/folders/16KGcFMtzekphF7qYhn1rdhg1unGsNV8b

Here's a slow-mo animation of the speaker in action.
![speaker](https://user-images.githubusercontent.com/8419308/46966341-b7966e00-d06a-11e8-97c0-321b23ff80c1.gif)

There are 21 frames, two corresponding to the min/max positions for each non-zero tick mark on the amplitude slider, and one for the zero-point. For example, suppose the amplitude slider is set to the mid-point, the the animation would be represented by speaker_-5.png through speaker_5.png.

**Comment by samreid** [comment]
I added the artwork in the preceding commit.  @arouinfar you can delete the images from Google Drive at your convenience.  

I'm also leaving this self-assigned to separate the two sources on screen 2 (they currently share the same node, this will need to be split up).

**Comment by arouinfar** [comment]
Thanks @samreid. The speaker assets have been deleted from Drive.

**Comment by arouinfar** [comment]
Looks great @samreid!!

**Comment by samreid** [comment]
I'm going to move this to scenery-phet for https://github.com/phetsims/sound/issues/6. There is no history on the PNG files (just one commit), so I don't think I need to transmit version history.
