### ISSUE TITLE
How should we depict the plane wave sources?

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#54]

**Comment by arouinfar** [comment]
I've emailed the graphic artist to set up a time to discuss the artwork needed for this sim. Once we meet, we'll track the artwork progress in the tasks repo.

**Comment by arouinfar** [comment]
The graphic artist requested some reference images for what these plane wave sources could look like. After thinking about the plane waves a bit more, I'd like to talk about the sources with the team before spending more time on the artwork.

Ripple tanks use a wooden rod to create plane waves, which could get tricky to animate, because the rod would need to hit the top of the water.

![image](https://user-images.githubusercontent.com/8419308/40747204-c71bb65e-6419-11e8-890c-2cef71b056a1.png)

Typical slit interference demos use a laser pointer as the source, which is (reasonably) collimated. I think we'd be safe using `laserPointerNode` without the glass element.

Sound is problematic. A normal speaker does not produce plane waves.  We could have some sort of piston that moves back and forth, but it wouldn't be recognizable as a speaker. 

Another option would be to continue using the point sources, as point sources appear planar when sufficiently far from the source. This may be a tougher sell, however, as the sources appear to emit a plane wave.

**Comment by samreid** [comment]
I should also mention that on the "slits" screen, we may be able to get away without drawing the plane wave source.

* How plane waves can be generated is not one of the learning goals we identified for the sim.
* "Once you are far away from a point source, it becomes planar" is a learning goal better covered by the first screen.
* It seems pretty clear that plane waves are coming in from the left--perhaps we don't need to "explain" how they got there.  And if we do add something, it may be more distracting than useful (depending on how good a fit we find).

**Comment by arouinfar** [comment]
Thanks @samreid.

> How plane waves can be generated is not one of the learning goals we identified for the sim.

Generally, I agree. I've considered using the point sources, but I wonder if they'd do any harm. Water in particular is problematic because it shows a droplet falling into the viewing window, which is at odds with the plane wave. The other sources do not explicitly show anything interacting with the viewing window, so they could be okay.

> "Once you are far away from a point source, it becomes planar" is a learning goal better covered by the first screen.

I think students can discover this on the Intro screen. However, if we use point sources on the Slits screen, I think we should explicitly document our assumption that the source is sufficiently far from the viewing window in the Teacher Tips.

> It seems pretty clear that plane waves are coming in from the left--perhaps we don't need to "explain" how they got there. And if we do add something, it may be more distracting than useful (depending on how good a fit we find).

We still need a source that is turned on/off, but I think it's a bit tricky. I agree that a rod hitting the water's surface or a piston creating sound waves could be distracting. That said, a water droplet creating a plane wave could be even more distracting.

**Comment by samreid** [comment]
What about just an on/of button (not showing water drops/speaker/laser)?

**Comment by arouinfar** [comment]
In the 6/28/18 design meeting we decided to go with a generic plane wave source. Each scene will have some sort of logo/icon to indicate that the source has changed.

SR sketched these options.
![image](https://user-images.githubusercontent.com/8419308/42064229-b12b658e-7af2-11e8-8ec2-1425a3163d34.png)

**Comment by arouinfar** [comment]
Self-assigning to work with graphic artist on the generic source.

**Comment by samreid** [comment]
The artwork task is https://github.com/phetsims/tasks/issues/939

**Comment by samreid** [comment]
On hold until we receive artwork.

**Comment by samreid** [comment]
Removed hold and assigned to @arouinfar to check status.

**Comment by arouinfar** [comment]
We had discussed this as a possible plane wave source:
![image](https://user-images.githubusercontent.com/8419308/46970129-735c9b00-d075-11e8-8d1e-afa957a22a11.png)

I'm a bit fuzzy on the details, and it looks like this unfortunately didn't make it into the meeting notes, but I believe we have these open questions:
* How do we indicate that the source has changed between scenes?
*  Do we put an icon on the wave source? Some possible icons would be a water drop, music note, and light bulb(?)
* Scene buttons could have the icon used on wave source (sources from first two screens don't make much sense here).
* Should scene icons on first three screens all match? (Probably!)

@samreid @ariel-phet do you remember anything about this discussion?

**Comment by arouinfar** [comment]
Thanks @samreid! I had a graveyard of rudimentary icons near the mockup in https://github.com/phetsims/wave-interference/issues/54#issuecomment-429965298, which reminded me of an earlier conversation. I'm not particularly tied to the idea of adding the icon, and you may be right that there are enough context cues elsewhere in the sim to indicate the scene has changed.

@samreid let's go ahead and implement the artwork and see how it looks in context. I've temporarily stored the assets on Drive:
https://drive.google.com/drive/u/0/folders/1ZFgKbO8OX3xj8iqWniIsJ44elTh1fr53

**Comment by samreid** [comment]
@arouinfar I committed the artwork to the wave-interference repo in the aforementioned commit, you can remove from Drive at your convenience.

**Comment by samreid** [comment]
Initial draft committed, @arouinfar can you please review on phettest and provide feedback?

**Comment by arouinfar** [comment]
I think it looks nice @samreid! Let's review it with the team in design meeting. I've deleted the asset file from Drive, so unassigning myself for now.

**Comment by arouinfar** [comment]
We reviewed the generic plane wave source in design meeting today. Here's a screenshot of what it looks like:
<img src="https://user-images.githubusercontent.com/8419308/47532438-9d7c3d00-d86d-11e8-9eca-94ae3ecc683f.png" width=200>

The team thought the source itself was fine, but Kathy suggested adding the scene selection icons to the source so that the context would be a bit more obvious. The metallic-looking icons may not have great contrast against the plane wave source, so I should mock up some options.

**Comment by arouinfar** [comment]
So far, this is the best option I've come up with. The rounded rectangles are 30x30 px with a white background at 60% opacity. 
![image](https://user-images.githubusercontent.com/8419308/47820390-fee75480-dd22-11e8-9967-bb61b3cf0adf.png)

@samreid can you give this a try? If you have any alternative ideas, I'd also be happy to mock them up!

**Comment by samreid** [comment]
First draft is committed and pushed, @arouinfar can you please test on phettest?

**Comment by arouinfar** [comment]
It definitely looks like the mockup, thanks @samreid. I'll tag for design meeting so the team can confirm whether or not this is the desired look.

**Comment by arouinfar** [comment]
@samreid I don't love the icons on the plane wave source. It feels a bit cluttered to me. I'm getting ready for interviews, and I'd like to test it out without the icons. Can we remove the icons for dev testing?

This seems like a pretty cosmetic choice, so I don't know that it would have serious implications on QA.

**Comment by arouinfar** [comment]
After further Slack discussion with @ariel-phet, I'd like to instead try adding a text label to the plane wave source. This was also an idea that was mentioned at the end of a previous design meeting. The proposed labels would be:
* Water Wave Generator
* Sound Generator
* Light Generator

Here's mockup showing the text. The font size is the same as Normal/Slow, and there is a white rectangle with 20% opacity behind the text to improve contrast/readability.
![image](https://user-images.githubusercontent.com/8419308/49547671-9733a480-f8a0-11e8-842d-b6fe07153444.png)

For i18n, this looks like a reasonable maxWidth:
![image](https://user-images.githubusercontent.com/8419308/49547726-c3e7bc00-f8a0-11e8-88ad-b17fa6a1f6f0.png)

**Comment by samreid** [comment]
@arouinfar said it would be nice to get this done before Monday so it could be used in initial interviews.

**Comment by samreid** [comment]
Implemented in above commit and ready for review and testing, @arouinfar can you please take a look?

**Comment by arouinfar** [comment]
@samreid looks pretty good. I have one tweak to suggest -- the maxWidth looks a bit too big. Can you make it a bit smaller so there's (roughly) equal whitespace above and below the string?

I'm thinking the string could expand until the magenta line:
![image](https://user-images.githubusercontent.com/8419308/49676535-502be780-fa37-11e8-9f9f-78e2ab6d81d3.png)

**Comment by arouinfar** [comment]
The maxWidth is not critical to fix before interviews, so removing the high priority tag.

**Comment by arouinfar** [comment]
👍
