### ISSUE TITLE
d sin(θ) = mλ

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#71]
I was measuring to check if d sin θ = mλ, and realized we don't have any instruments in the sim for measuring angle.  One of the learning goals from the design doc is:

> In the light panel, predict the locations of the fringes that appear on the screen using d*sin(θ) = mλ. Use the tape measure to verify your predictions.

Should we provide a protractor, or other angle-measuring device?  It could be as simple as a readout of m=... and θ=... near the maxima or minima.

**Comment by arouinfar** [comment]
@samreid while clunky, students can use the tape measure to measure the sides of a right triangle, and then determine the angle from there. A protractor would certainly be more efficient.

I think m is straightforward enough without a readout. A theta readout would certainly be useful, but I wonder if it would give away too much information.

Let's discuss more at the next design meeting.

**Comment by arouinfar** [comment]
In today's design meeting we decided against adding a protractor.

* The protractor can be a bit tricky because the origin may not be clear.
* The goal is not for students to discover the equation. Instead, we hope students may observe particular relationships (slit spacing/maxima spacing). The instructor can then layer on the equation, and students can design experiments to verify.
* Tape measure is more consistent with lab experience
* Toolbox is already cramped.
