### ISSUE TITLE
What should the timer display when its value exceeds its max?

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#94]
For instance, the timer display is sized to display a max value of 999.99 seconds and looks like so:

![image](https://user-images.githubusercontent.com/679486/43922181-37b5a066-9bdb-11e8-9d44-dcb8fa627c8d.png)

After it goes 0.01 seconds further, should it:

a) shrink the display?
b) reset back to 0.0?
c) stop reading at 999.99 s
d) something else?

**Comment by samreid** [comment]
@ariel-phet suggested to stop reading at 999.99s (or whatever max).  Sounds great to the rest of the team.

**Comment by samreid** [comment]
@jonathanolson can you please also review this commit together with https://github.com/phetsims/scenery-phet/issues/372 ?

**Comment by samreid** [comment]
@Denz1994 has been assigned review for the stopwatch.  @Denz1994 can you please review this part as well?

**Comment by Denz1994** [comment]
My comments in https://github.com/phetsims/capacitor-lab-basics/issues/244 should also be noted in this issue (https://github.com/phetsims/capacitor-lab-basics/issues/244#issuecomment-424449014 and https://github.com/phetsims/capacitor-lab-basics/issues/244#issuecomment-424449047).

Otherwise the `maxValue` functionality behaves well.

**Comment by samreid** [comment]
Thanks @Denz1994, it seems we can close this issue and continue in https://github.com/phetsims/capacitor-lab-basics/issues/244
